### ISSUE TITLE
How to detect language

### ISSUE THREAD

**Issue by mevartma** [kljensen/snowball#3]
Can you provide example, how to use this package to detect language from stream of text

**Comment by kljensen** [comment]
Hi - alas, it does not do that

**Comment by mevartma** [comment]
I have run your test, after i run this command "go get github.com/chrisport/go-lang-detector/langdet":
package main

import (
  "fmt"
  "github.com/chrisport/go-lang-detector/langdet"
)

func main() {
  detector := langdet.NewDefaultDetector()
  testString := "do not care about my car"
  result := detector.GetClosestLanguage(testString)
  fmt.Println(result)
}

and this is the result:
undefined: langdet.NewDefaultDetector

**Comment by kljensen** [comment]
I think you're posting in the wrong project ;)
