### ISSUE TITLE
Badly named file

### ISSUE THREAD

**Issue by metal3d** [kljensen/snowball#8]
Hi

You named romance/common_testing.go instead of romance/common_test.go

This files is not seen as a testing package and is compiled with the whole package.

So, when I use your package using flag package, using "-h" flag, I see the entire test.XXX flags.

I forked your package to rename the file and it works.

BTW: Thanks for your work, it works great

**Comment by kljensen** [comment]
Fixed in efb38e9d328445c394866a548fd43938f5f1915f
